version: "3.9"
services:
  java-swing-app:
    image: java-swing-app
    container_name: java-swing-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - app-networks

networks:
  app-networks:
